server:
  port: 8088
spring:
  application:
    name: demo-provider
dubbo:
  application:
    name: demo-provider
  protocol:
    name: dubbo
    port: 8888
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181